name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.0

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test
